Repository practice-uffs/web-feedback, pull requests merged in 2020-08, with the labels that each got.

#83 fix: corrige problema com campo 'hidden'
  app/Http/Controllers/ItemController.php
  resources/sass/components/header.scss
  resources/views/item/edit.blade.php
Labels: bug

#84 feat: replaces HOMER with "hand-crafted" dashboard
  app/Http/Controllers/ItemController.php
  resources/js/components/CommentListComponent.vue
  resources/js/components/ReactionListComponent.vue
  resources/sass/components/header.scss
  resources/sass/components/timeline.scss
  resources/views/item/index.blade.php
  resources/views/item/show.blade.php
Labels: enhancement, refactor

#87 feat(service): implements service create
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/ItemController.php
  resources/css/spacing-utility.css
  resources/js/app.js
  resources/js/components/ServiceForm.vue
  resources/sass/_utilities.scss
  resources/sass/_variables.scss
  resources/sass/app.scss
  resources/sass/components/button.scss
  resources/sass/components/header.scss
  resources/sass/login.scss
  resources/views/auth/login.blade.php
  resources/views/item/edit.blade.php
  resources/views/item/index.blade.php
  resources/views/item/show.blade.php
Labels: enhancement, refactor

#88 feat(feedback): adds feedback creation modal
  app/Http/Controllers/API/CategoryController.php
  app/Http/Controllers/API/ItemController.php
  app/Http/Controllers/API/LocationController.php
  resources/js/app.js
  resources/js/components/CommentListComponent.vue
  resources/js/components/FeedbackFormComponent.vue
  resources/js/components/ReactionListComponent.vue
  resources/js/components/ServiceFormComponent.vue
  resources/js/components/base/Modal.vue
  resources/sass/app.scss
  resources/sass/components/modal.scss
  resources/views/item/create.blade.php
  resources/views/item/index.blade.php
  resources/views/item/show.blade.php
  routes/api.php
Labels: enhancement, refactor

#89 refactor(service): implements service creation using base modal
  resources/js/app.js
  resources/js/components/FeedbackFormComponent.vue
  resources/js/components/ServiceFormComponent.vue
  resources/js/components/base/Modal.vue
  resources/sass/_utilities.scss
  resources/views/item/index.blade.php
Labels: refactor

#90 feat: implements Specification entity
  app/Http/Controllers/API/ItemController.php
  app/Item.php
  app/Specification.php
  database/migrations/2020_07_06_185039_create_items_table.php
  database/migrations/2020_08_07_205415_create_specifications_table.php
Labels: enhancement

#98 feat: shows users avatar
  public/favicon.ico
  public/img/avatars/avatar-1.png
  public/img/avatars/avatar-2.png
  public/img/avatars/avatar-3.png
  public/img/avatars/avatar-4.png
  resources/js/app.js
  resources/js/components/ReactionListComponent.vue
  resources/sass/components/header.scss
  resources/views/item/create.blade.php
  resources/views/item/edit.blade.php
  resources/views/item/index.blade.php
  resources/views/item/show.blade.php
  resources/views/layouts/headerAuth.blade.php
Labels: enhancement

#99 feat: Change API architecture
  app/Http/Controllers/API/FeedbackController.php
  app/Http/Controllers/API/ItemController.php
  app/Http/Controllers/API/ServiceController.php
  app/Http/Controllers/ItemController.php
  app/Http/Resources/CommentResource.php
  app/Http/Resources/FeedbackResource.php
  app/Http/Resources/ServiceResource.php
  database/migrations/2019_08_07_205415_create_specifications_table.php
  resources/js/components/AsyncHelperComponent.vue
  resources/js/components/FeedbackFormComponent.vue
  resources/js/components/ServiceFormComponent.vue
  resources/views/item/index.blade.php
  routes/api.php
  routes/web.php
Labels: enhancement
